# conda env create -f environment.yml
name: csr3d
channels:
  - conda-forge
dependencies:
  - python=3
  - scipy
  - numpy
  - numba
  - ipykernel
  - jupyterlab
  - matplotlib-base
  - h5py
  - mpmath
  # For testing and comparisons
  - pip
  - pip:
    - git+git://github.com/ChristopherMayes/PyCSR3D
    - git+git://github.com/weiyuanlou/PyCSR2D

